# Generated by Django 4.2.7 on 2024-03-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
