# Generated by Django 4.2.7 on 2024-03-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0004_bed_bed_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
