# Generated by Django 4.2.7 on 2024-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0005_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField()),
                ('hostel_name', models.CharField(max_length=255)),
                ('room_id', models.IntegerField()),
                ('bed_id', models.IntegerField()),
                ('bed_price_per_day', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
            ],
        ),
    ]
