# Generated by Django 4.2.7 on 2024-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0009_remove_hostel_norooms_alter_hostel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
